name: Bounties
version: 1.3
main: me.playwithnathan.Bounties
api-version: 1.18
depend: [ Vault, PlaceholderAPI ]
authors: [ playwithnathan ]
description: A bounties plugin
commands:
  bounties:
    description: Use the bounties plugin
    usage: /bounties
  bounty:
    description: An alias for /bounties
    usage: /bounty